# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  arvalinvoicerapi:
    image: arvalinvoicerapi
    build:
      context: .
      dockerfile: Arval.Invoicer.API/Dockerfile
    ports:
      - 5041:5041
