# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  zaptecinvoicerapi:
    image: zaptecinvoicerapi
    build:
      context: .
      dockerfile: Arval.Invoicer.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5041:5041
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
